services:
  nats:
    image: nats:latest
    entrypoint: /nats-server
    command: "-js"
    ports:
      - "4222:4222"
      - "8222:8222"
      -
  bridge:
    build: ./bridge
    environment:
      log_level: debug
      nats_server: nats://nats:4222

  handler:
    build: ./handler
    environment:
      log_level: debug
      nats_server: nats://nats:4222